import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Search, User } from "lucide-react";
import Link from 'next/link';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        <nav className="fixed top-0 left-0 right-0 h-16 bg-white border-b border-gray-200 z-50 flex items-center justify-between px-6">
          <Link href="/" className="font-bold text-xl text-rose-500 tracking-tight cursor-pointer">
            Eventos MVP
          </Link>
          <div className="flex items-center gap-4">
            <Link 
              href="/create" 
              className="hidden sm:block text-sm font-semibold text-gray-700 hover:bg-gray-100 px-4 py-2 rounded-full transition"
            >
              Pon tu evento en Airbnb
            </Link>
            <Link 
              href="/create"
              className="bg-rose-600 text-white text-sm font-semibold px-4 py-2 rounded-full hover:bg-rose-700 transition shadow-sm"
            >
              Publicar Evento
            </Link>
            <button className="flex items-center gap-2 border border-gray-300 rounded-full p-2 hover:shadow-md transition text-gray-600 ml-2">
              <User className="w-5 h-5" />
            </button>
          </div>
        </nav>
        <div className="pt-16 h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
